### ISSUE TITLE
Something not going to plan with repeating pulses

### ISSUE THREAD

**Issue by WilliamDaoyiCheng** [MaxFalkenberg/AF-Model#3]
There's something wrong on my end where a repeated pulse does not reach the end of the grid and stops.

code for me that leads to this problem:

```python
a = main_test.tissue()
a.set_pulse(300)
a.pulse()
a.propagate(1500)
a.save("testfile3")

b = animator.Visual("testfile3")
b.convert()
b.show_animation()
```

It could be something wrong with b.convert() but looking through b.file_data, I think the problem might be in main_test.py.

**Comment by MaxFalkenberg** [comment]
Resolved: Empty lists were being formatted as floats. Changed data type to int32. Working for me now.

**Comment by MaxFalkenberg** [comment]
Resolved: The empty arrays were being saved as a float data type. Changed data type to int32. Animation is now working for me.

**Comment by WilliamDaoyiCheng** [comment]
I've tried the new main_test.py and I'm still seeing the same strange behaviour. I've used the same parameters as in the above example in the attached gif.

![weird_repeat](https://cloud.githubusercontent.com/assets/13243893/19224405/18381510-8e7d-11e6-840b-f7af1e497fd7.gif)
